FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o spider ./main.go
RUN go test -v ./...

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/crawler .

CMD ["./crawler"]
